services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src # ton src local = src dans le conteneur
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://dev:devpassword@db:5432/taskboard
      NODE_ENV: development
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src # même principe
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:4000
    depends_on:
      - api
